FROM node:20

WORKDIR /backend

# Copia solo los archivos de dependencias primero para aprovechar el cache de Docker
COPY package*.json ./

RUN npm install

# Ahora copia el resto del código
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]